version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: videogames-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: videogamesdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: videogames-api
    environment:
      DB_URL: jdbc:mysql://db:3306/videogamesdb
      DB_USERNAME: dbuser
      DB_PASSWORD: dbpassword
    ports:
      - "8789:8080"
    depends_on:
      - db
    restart: always

volumes:
  db_data: